if (!workbox) {
    // Precache manifest generated by the vue cli for static assets like .js,.css,.png etc.
    workbox.precaching.precacheAndRoute(self.__precacheManifest);

    // install new service worker when it is being updated, then reload page.
    self.addEventListener('message', msg => {
        if (msg.data.action === 'skipWaiting') {
            self.skipWaiting();
        }
    });

    workbox.routing.registerRoute(
        /^https:\/\/fonts\.googleapis\.com/,
        new workbox.strategies.CacheFirst({
            cacheName: 'google-fonts',
            cacheableResponses: {
                statuses: [0, 200]
            }
        })
    );

    workbox.routing.registerRoute(
        /^https:\/\/fonts\.gstatic\.com/,
        new workbox.strategies.CacheFirst({
            cacheName: 'google-fonts',
            cacheableResponses: {
                statuses: [0, 200]
            }
        })
    );

    // workbox.routing.registerRoute(new RegExp(window.config + '/api/operative.*'),
    workbox.routing.registerRoute(
        new RegExp('.*api.*'),
        new workbox.strategies.NetworkFirst({
            cacheName: 'apis',
            cacheableResponses: {
                statuses: [0, 200]
            },
            networkTimeoutSeconds: 3,
            plugins: [
                new workbox.expiration.Plugin({
                    maxEntries: 50
                })
            ]
        })
    );
}
